volumes:
  pgdata:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      LANG: ru_RU.UTF-8
      LC_MESSAGES: C
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=ru-RU --lc-messages='C'"
    ports:
      - 15432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]